#Global alert
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: port.scan
spec:
  aggregateBy:
  - source_namespace
  - dest_name_aggr
  - source_name_aggr
  - dest_namespace
  - num_flows
  condition: gte
  dataSet: flows
  description: Port scan detected!!!
  field: num_flows
  lookback: 1h0m0s
  metric: sum
  period: 1m0s
  query: ("dest_port" != 53 AND ("dest_namespace" = "kube-system" AND "dest_labels.labels"
    = "k8s-app=kube-dns"))
  severity: 50
  summary: Scan from ${source_namespace}/${source_name_aggr} to ${dest_namespace}/${dest_name_aggr}
    flows detected ${num_flows}
  threshold: 1
